### ISSUE TITLE
File removal widget

### ISSUE THREAD

**Issue by lenormf** [ergoithz/browsepy#10]
Hi,

Looking at the screenshot provided, I was under the impression that I would be able to remove files using the web UI, but the buttons don't appear when I browse directories the server can remove files in. Was this feature lost during the transition to `0.5`?

Thanks.

**Comment by ergoithz** [comment]
You definitely can, looking at "--help" output http://ergoithz.github.io/browsepy/quickstart.html#usage you wild find the "--removable" option. It accepts a directory path, and all files under this location will show the appropriate "remove" button.

**Comment by lenormf** [comment]
Thanks, I completely missed it. For some reason I expected that to be a plugin rather than a core feature activated with an option.
