### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by BillVeusees** [ergoithz/browsepy#19]
Hi there,

Thanks for the hard work !

I only miss a password protection feature. Something as simple as one shared password for everyone.

Have you thought of this for your roadmap ?

Thanks

**Comment by BillVeusees** [comment]
I have forked and tried my way to implement a simple password protection, but it is untested (as I cannot find how to start properly the app without having  an error

`
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "browsepy/__main__.py", line 13, in <module>
    from . import app, compat
ImportError: attempted relative import with no known parent package
`
So I will issue a pull request so you can do the last mile ?

**Comment by ergoithz** [comment]
I use a simple HTTP authentication (configured on a proxy server like NGINX) over HTTPS (to make it safe).

**A note about extra functionality:** browsepy's feature scope is closed, but any extra functionality could be added as plugin (as long as it complies a few rules http://ergoithz.github.io/browsepy/builtin_plugins.html#contributing-builtin-plugins). Indeed a proper authentication plugin is on our roadmap.
