### ISSUE TITLE
Flask from_envvar reads only uppercase values

### ISSUE THREAD

**Issue by kovalevfm** [ergoithz/browsepy#28]
http://flask.pocoo.org/docs/0.12/config/#configuring-from-files
> The configuration files themselves are actual Python files. Only values in uppercase are actually stored in the config object later on. So make sure to use uppercase letters for your config keys.

```python
app.config.update(
    directory_base=compat.getcwd(),
    directory_start=None,
...
if 'BROWSEPY_SETTINGS' in os.environ:
   app.config.from_envvar('BROWSEPY_SETTINGS')
```
Lowercase options like `directory_base` can't be read from configuration file passed with os env variable

**Comment by kovalevfm** [comment]
I found browsepy/appconfig.py, should work

**Comment by ergoithz** [comment]
There is a planned deprecation process for lowercase config variables, appconfig is the workaround until we get rid of them.
