### ISSUE TITLE
APPLICATION_ROOT is not working

### ISSUE THREAD

**Issue by stefanoborini** [ergoithz/browsepy#3]
The documentation suggests to use APPLICATION_ROOT to modify the position of the application so that it runs on another URL. Any attempt made to make it work by setting app.config["APPLICATION_ROOT"] didn't produce any result, so either there's a problem in the documentation, or the APPLICATION_ROOT variable is not honored somehow (either by flask or browsepy)

**Comment by stefanoborini** [comment]
I found a better strategy in using gunicorn, and the following flask snippet 

http://flask.pocoo.org/snippets/35/

**Comment by ergoithz** [comment]
APPLICATION_ROOT is used only by flask, not being used by browsepy code. And yes, as your link points to, the wsgi environ-dict values for "PATH_INFO" and "SCRIPT_NAME" are honored first, so best way to ensure your URL base gets rewritten is to wrap the flask application using a wsgi middleware.

Anyway, README is confusing and should be improved with this info, I'll do soon as possible.
