### ISSUE TITLE
... HTTPS?

### ISSUE THREAD

**Issue by wdbm** [ergoithz/browsepy#31]
Hey there! `browsepy` is awesome! Would you consider changing it such that it can run via HTTPS?

**Comment by ergoithz** [comment]
Browsepy is a WSGI application which provides a non-production-ready HTTP server for convenience (the Flask testing HTTP server).

If you need HTTPS, or want to deploy browsepy on a productive environment, you should launch it with a proper WSGI application server like uwsgi, paste or gunicorn. Or if you don't care but still want HTTPS (like me) you can use NGINX to proxy your HTTPS request to a local HTTP port (and handle  stuff like Basic Authentication, headers and so on).

Example (using uwsgi):

1.  Install uwsgi using pip `pip install uwsgi` (ideally inside your venv, where browsepy is installed).
2.  Run browsepy via HTTPS with `uwsgi -w browsepy:app --https 0.0.0.0:8080,CERT,KEY`

**Comment by wdbm** [comment]
Ah thanks a lot for these details, that is super helpful. I've now got a basic grasp of running using Gunicorn. Sorry for raising an issue!
