### ISSUE TITLE
appending path to base-url does not work

### ISSUE THREAD

**Issue by fschlimb** [ergoithz/browsepy#4]
Assume the server runs on http://10.0.1.1:8080/ and the served root directory has sub-folder "foo".
Intuitively requesting http://10.0.0.1:8080/foo should show the content of that folder. A url-not-found is displayed instead. browsepy surprisingly inserts "browse" after the root url.

**Comment by ergoithz** [comment]
This is a design choose and the only way to avoid collisions with browsepy actions such as 'open', 'download', 'remove' and so on.

Without this prefix, any folder called download would became non-accesible, or alternatively you won't be able to download anything.
